version: '3.9'
services:
  postgres_keycloak:
    image: postgres:latest
    container_name: postgres_keycloak
    hostname: postgres_keycloak
    ports:
      - 8001:5432
    volumes:
      - ./postgres_keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${KEYCLOAK_POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - issn-network

  postgres_issn:
    image: postgres:latest
    container_name: postgres_issn
    hostname: postgres_issn
    ports:
      - ${APP_POSTGRES_PORT}:5432
    volumes:
      - ./postgres_issn_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${APP_POSTGRES_DB}
      POSTGRES_USER: ${APP_POSTGRES_USER}
      POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      - issn-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    hostname: keycloak
    command: start-dev --http-relative-path /auth
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_DATABASE_HOST: postgres_keycloak
      KEYCLOAK_DATABASE_PORT: 8001
      KEYCLOAK_DATABASE_NAME: ${KEYCLOAK_POSTGRES_DB}
      KEYCLOAK_DATABASE_USER: ${KEYCLOAK_POSTGRES_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_ENABLE_STATISTICS: true
      KEYCLOAK_DATABASE_VENDOR: postgresql
      PROXY_ADDRESS_FORWARDING: "true"
      KC_PROXY: edge
    ports:
      - 8080:8080
    depends_on:
      - postgres_keycloak
    restart: unless-stopped
    networks:
      - issn-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - issn-network

  auth:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    container_name: auth
    env_file:
      - .env
    depends_on:
      - keycloak
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:dev auth
    restart: unless-stopped
    networks:
      - issn-network

  presence:
    build:
      context: ./
      dockerfile: ./apps/presence/Dockerfile
    container_name: presence
    env_file:
      - .env
    depends_on:
      - postgres_issn
      - keycloak
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:dev presence
    restart: unless-stopped
    networks:
      - issn-network

  persons:
    build:
      context: ./
      dockerfile: ./apps/persons/Dockerfile
    container_name: persons
    env_file:
      - .env
    depends_on:
      - postgres_issn
      - keycloak
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:dev persons
    restart: unless-stopped
    networks:
      - issn-network

  api:
    build:
      context: ./
      dockerfile: ./apps/issn-api/Dockerfile
    container_name: api
    ports:
      - 9000:9000
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres_issn
      - postgres_keycloak
      - keycloak
      - auth
      - presence
      - persons
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:dev api
    restart: on-failure
    networks:
      - issn-network

volumes:
  postgres_keycloak_data:
    driver: local
  postgres_issn_data:
    driver: local
  rabbitmq:

networks:
  issn-network:
    external: true
